##Prepare the Document for Analysis##
setwd ("~/Documents/GitHub/Jekyll-and-Hyde/")
text.v <- scan("edwardh.txt", what="character", sep="\n")
start.v <-which(text.v == "STORY OF THE DOOR")
end.v <-2135L
start.metadata.v <-text.v[1:start.v-1]
end.metadata.v <- text.v[(end.v+1):length(text.v)]
metadata.v <- c(start.metadata.v, end.metadata.v)
novel.lines.v <- text.v[start.v:end.v]
novel.v <- paste(novel.lines.v, collapse=" ")
novel.lower.v <- tolower(novel.v)
hyde.words.1 <-strsplit(novel.lower.v, "\\W")
hyde.words.v <- unlist(hyde.words.1)
not.blanks.v <- which(hyde.words.v!="")
hyde.words.v <- hyde.words.v[not.blanks.v]
hyde.freqs.t <-table(hyde.words.v)
n.time.v <-seq(1:length(hyde.words.v))

##Create Plot for Topic 0##
letter.v <-which(hyde.words.v == "letter")
doctor.v <-which(hyde.words.v == "doctor")
client.v <-which(hyde.words.v == "client")
friends.v <-which(hyde.words.v == "friends")
mark.v <-which(hyde.words.v == "mark")
bottle.v <-which(hyde.words.v == "bottle")
handed.v <-which(hyde.words.v == "handed")
escape.v <-which(hyde.words.v == "escape")
judge.v <-which(hyde.words.v == "judge")
swear.v <-which(hyde.words.v == "swear")
topic.zero.v <-c(letter.v, doctor.v, client.v, friends.v, mark.v, bottle.v, handed.v, escape.v, judge.v, swear.v)
zero.count.v <-rep(NA,length(n.time.v))
zero.count.v[topic.zero.v] <- 1
plot(zero.count.v, main="Dispersion plot of Topic 0 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 0", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 1##
city.v <-which(hyde.words.v == "city")
ten.v <-which(hyde.words.v == "ten")
corner.v <-which(hyde.words.v == "corner")
along.v <-which(hyde.words.v == "along")
bystreet.v <-which(hyde.words.v == "by-street")
interest.v <-which(hyde.words.v == "interest")
sounds.v <-which(hyde.words.v == "sounds")
mind.v <-which(hyde.words.v == "mind")
two.v <-which(hyde.words.v == "two")
face.v <-which(hyde.words.v == "face")
topic.one.v <-c(city.v, ten.v, corner.v, along.v, bystreet.v, interest.v, sounds.v, mind.v, two.v, face.v)
one.count.v <-rep(NA,length(n.time.v))
one.count.v[topic.one.v] <- 1
plot(one.count.v, main="Dispersion plot of Topic 1 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 1", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 2##
said.v <-which(hyde.words.v == "said")
utterson.v <-which(hyde.words.v == "utterson")
man.v <-which(hyde.words.v == "man")
one.v <-which(hyde.words.v == "one")
jekyll.v <-which(hyde.words.v == "jekyll")
hyde.v <-which(hyde.words.v == "hyde")
lawyer.v <-which(hyde.words.v == "lawyer")
upon.v <-which(hyde.words.v == "upon")
like.v <-which(hyde.words.v == "like")
would.v <-which(hyde.words.v == "would")
topic.two.v <-c(said.v, utterson.v, man.v, one.v, jekyll.v, hyde.v, lawyer.v, upon.v, like.v, would.v)
two.count.v <-rep(NA,length(n.time.v))
two.count.v[topic.two.v] <- 1
plot(two.count.v, main="Dispersion plot of Topic 2 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 2", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 3##
maid.v <-which(hyde.words.v == "maid")
victim.v <-which(hyde.words.v == "victim")
heavy.v <-which(hyde.words.v == "heavy")
stick.v <-which(hyde.words.v == "stick")
lane.v <-which(hyde.words.v == "lane")
gentleman.v <-which(hyde.words.v == "gentleman")
body.v <-which(hyde.words.v == "body")
seen.v <-which(hyde.words.v == "seen")
broken.v <-which(hyde.words.v == "broken")
particularly.v <-which(hyde.words.v == "particularly")
topic.three.v <-c(maid.v, victim.v, heavy.v, stick.v, lane.v, gentleman.v, body.v, seen.v, broken.v, particularly.v)
three.count.v <-rep(NA,length(n.time.v))
three.count.v[topic.three.v] <- 1
plot(three.count.v, main="Dispersion plot of Topic 3 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 3", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 4##
guest.v <-which(hyde.words.v == "guest")
clerk.v <-which(hyde.words.v == "clerk")
document.v <-which(hyde.words.v == "document")
death.v <-which(hyde.words.v == "death")
sir.v <-which(hyde.words.v == "sir")
note.v <-which(hyde.words.v == "note")
tempted.v <-which(hyde.words.v == "tempted")
autograph.v <-which(hyde.words.v == "autograph")
public.v <-which(hyde.words.v == "public")
handwriting.v <-which(hyde.words.v == "handwriting")
topic.four.v <-c(guest.v, clerk.v, document.v, death.v, sir.v, note.v, tempted.v, autograph.v, public.v, handwriting.v)
four.count.v <-rep(NA,length(n.time.v))
four.count.v[topic.four.v] <- 1
plot(four.count.v, main="Dispersion plot of Topic 4 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 4", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 5##
two.v <-which(hyde.words.v == "two")
even.v <-which(hyde.words.v == "even")
life.v <-which(hyde.words.v == "life")
die.v <-which(hyde.words.v == "die")
evil.v <-which(hyde.words.v == "evil")
pleasures.v <-which(hyde.words.v == "pleasures")
months.v <-which(hyde.words.v == "months")
made.v <-which(hyde.words.v == "made")
side.v <-which(hyde.words.v == "side")
moral.v <-which(hyde.words.v == "moral")
topic.five.v <-c(two.v, even.v, life.v, die.v, evil.v, pleasures.v, months.v, made.v, side.v, moral.v)
five.count.v <-rep(NA,length(n.time.v))
five.count.v[topic.five.v] <- 1
plot(five.count.v, main="Dispersion plot of Topic 5 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 5", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 6##
visitor.v <-which(hyde.words.v == "visitor")
curiosity.v <-which(hyde.words.v == "curiosity")
ordinary.v <-which(hyde.words.v == "ordinary")
remember.v <-which(hyde.words.v == "remember")
sense.v <-which(hyde.words.v == "sense")
unknown.v <-which(hyde.words.v == "unknown")
person.v <-which(hyde.words.v == "person")
struck.v <-which(hyde.words.v == "struck")
set.v <-which(hyde.words.v == "set")
conduct.v <-which(hyde.words.v == "conduct")
topic.six.v <-c(visitor.v, curiosity.v, ordinary.v, remember.v, sense.v, unknown.v, person.v, struck.v, set.v, conduct.v)
six.count.v <-rep(NA,length(n.time.v))
six.count.v[topic.six.v] <- 1
plot(six.count.v, main="Dispersion plot of Topic 6 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 6", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 7##
many.v <-which(hyde.words.v == "many")
liked.v <-which(hyde.words.v == "liked")
others.v <-which(hyde.words.v == "others")
ill.v <-which(hyde.words.v == "ill")
clear.v <-which(hyde.words.v == "clear")
secrets.v <-which(hyde.words.v == "secrets")
past.v <-which(hyde.words.v == "past")
things.v <-which(hyde.words.v == "things")
chief.v <-which(hyde.words.v == "chief")
friendship.v <-which(hyde.words.v == "friendship")
topic.seven.v <-c(many.v, liked.v, others.v, ill.v, clear.v, secrets.v, past.v, things.v, chief.v, friendship.v)
seven.count.v <-rep(NA,length(n.time.v))
seven.count.v[topic.seven.v] <- 1
plot(seven.count.v, main="Dispersion plot of Topic 7 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 7", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 8##
creature.v <-which(hyde.words.v == "creature")
evil.v <-which(hyde.words.v == "evil")
horror.v <-which(hyde.words.v == "horror")
countenance.v <-which(hyde.words.v == "countenance")
drug.v <-which(hyde.words.v == "drug")
hours.v <-which(hyde.words.v == "hours")
beyond.v <-which(hyde.words.v == "beyond")
life.v <-which(hyde.words.v == "life")
sensations.v <-which(hyde.words.v == "sensations")
pangs.v <-which(hyde.words.v == "pangs")
topic.eight.v <-c(creature.v, evil.v, horror.v, countenance.v, drug.v, hours.v, beyond.v, life.v, sensations.v, pangs.v)
eight.count.v <-rep(NA,length(n.time.v))
eight.count.v[topic.eight.v] <- 1
plot(eight.count.v, main="Dispersion plot of Topic 8 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 8", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 9##
poole.v <-which(hyde.words.v == "poole")
sir.v <-which(hyde.words.v == "sir")
voice.v <-which(hyde.words.v == "voice")
butler.v <-which(hyde.words.v == "butler")
thats.v <-which(hyde.words.v == "that's")
its.v <-which(hyde.words.v == "it's")
master.v <-which(hyde.words.v == "master")
servant.v <-which(hyde.words.v == "servant")
candle.v <-which(hyde.words.v == "candle")
theres.v <-which(hyde.words.v == "there's")
topic.nine.v <-c(poole.v, sir.v, voice.v, butler.v, thats.v, its.v, master.v, servant.v, candle.v, theres.v)
nine.count.v <-rep(NA,length(n.time.v))
nine.count.v[topic.nine.v] <- 1
plot(nine.count.v, main="Dispersion plot of Topic 9 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 9", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 10##
drawer.v <-which(hyde.words.v == "drawer")
letter.v <-which(hyde.words.v == "letter")
book.v <-which(hyde.words.v == "book")
understood.v <-which(hyde.words.v == "understood")
colleague.v <-which(hyde.words.v == "colleague")
midnight.v <-which(hyde.words.v == "midnight")
contents.v <-which(hyde.words.v == "contents")
reason.v <-which(hyde.words.v == "reason")
rose.v <-which(hyde.words.v == "rose")
powders.v <-which(hyde.words.v == "powders")
topic.ten.v <-c(drawer.v, letter.v, book.v, understood.v, colleague.v, midnight.v, contents.v, reason.v, rose.v, powders.v)
ten.count.v <-rep(NA,length(n.time.v))
ten.count.v[topic.ten.v] <- 1
plot(ten.count.v, main="Dispersion plot of Topic 10 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 10", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 11##
street.v <-which(hyde.words.v == "street")
woman.v <-which(hyde.words.v == "woman")
fog.v <-which(hyde.words.v == "fog")
seen.v <-which(hyde.words.v == "seen")
shop.v <-which(hyde.words.v == "shop")
many.v <-which(hyde.words.v == "many")
brown.v <-which(hyde.words.v == "brown")
cab.v <-which(hyde.words.v == "cab")
latter.v <-which(hyde.words.v == "latter")
lamps.v <-which(hyde.words.v == "lamps")
topic.eleven.v <-c(street.v, woman.v, fog.v, seen.v, shop.v, many.v, brown.v, cab.v, latter.v, lamps.v)
eleven.count.v <-rep(NA,length(n.time.v))
eleven.count.v[topic.eleven.v] <- 1
plot(eleven.count.v, main="Dispersion plot of Topic 11 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 11", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 12##
draught.v <-which(hyde.words.v == "draught")
supply.v <-which(hyde.words.v == "supply")
wonderful.v <-which(hyde.words.v == "wonderful")
loathed.v <-which(hyde.words.v == "loathed")
finally.v <-which(hyde.words.v == "finally")
ecstasy.v <-which(hyde.words.v == "ecstasy")
love.v <-which(hyde.words.v == "love")
fall.v <-which(hyde.words.v == "fall")
days.v <-which(hyde.words.v == "days")
fallen.v <-which(hyde.words.v == "fallen")
topic.ten.v <-c(draught.v, supply.v, wonderful.v, loathed.v, finally.v, ecstasy.v, love.v, fall.v, days.v, fallen.v)
twelve.count.v <-rep(NA,length(n.time.v))
twelve.count.v[topic.twelve.v] <- 1
plot(twelve.count.v, main="Dispersion plot of Topic 12 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 12", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 13##
door.v <-which(hyde.words.v == "door")
several.v <-which(hyde.words.v == "several")
times.v <-which(hyde.words.v == "times")
turned.v <-which(hyde.words.v == "turned")
theatre.v <-which(hyde.words.v == "theatre")
cabinet.v <-which(hyde.words.v == "cabinet")
may.v <-which(hyde.words.v == "may")
body.v <-which(hyde.words.v == "body")
lying.v <-which(hyde.words.v == "lying")
clothes.v <-which(hyde.words.v == "clothes")
topic.thirteen.v <-c(door.v, several.v, times.v, turned.v, theatre.v, cabinet.v, may.v, body.v, lying.v, clothes.v)
thirteen.count.v <-rep(NA,length(n.time.v))
thirteen.count.v[topic.thirteen.v] <- 1
plot(thirteen.count.v, main="Dispersion plot of Topic 13 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 13", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 14##
hyde.v <-which(hyde.words.v == "hyde")
edward.v <-which(hyde.words.v == "edward")
jekyll.v <-which(hyde.words.v == "jekyll")
cast.v <-which(hyde.words.v == "cast")
double.v <-which(hyde.words.v == "double")
terror.v <-which(hyde.words.v == "terror")
soho.v <-which(hyde.words.v == "soho")
body.v <-which(hyde.words.v == "body")
still.v <-which(hyde.words.v == "still")
vain.v <-which(hyde.words.v == "vain")
topic.fourteen.v <-c(door.v, several.v, times.v, turned.v, theatre.v, cabinet.v, may.v, body.v, lying.v, clothes.v)
fourteen.count.v <-rep(NA,length(n.time.v))
fourteen.count.v[topic.fourteen.v] <- 1
plot(fourteen.count.v, main="Dispersion plot of Topic 14 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 14", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 15##
clothes.v <-which(hyde.words.v == "clothes")
enter.v <-which(hyde.words.v == "enter")
smiled.v <-which(hyde.words.v == "smiled")
lighted.v <-which(hyde.words.v == "lighted")
gallows.v <-which(hyde.words.v == "gallows")
conceal.v <-which(hyde.words.v == "conceal")
chattering.v <-which(hyde.words.v == "chattering")
fury.v <-which(hyde.words.v == "fury")
boldness.v <-which(hyde.words.v == "boldness")
closed.v <-which(hyde.words.v == "closed")
topic.fifteen.v <-c(door.v, several.v, times.v, turned.v, theatre.v, cabinet.v, may.v, body.v, lying.v, clothes.v)
fifteen.count.v <-rep(NA,length(n.time.v))
fifteen.count.v[topic.fifteen.v] <- 1
plot(fifteen.count.v, main="Dispersion plot of Topic 15 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 15", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 16##
enfield.v <-which(hyde.words.v == "clothes")
cheque.v <-which(hyde.words.v == "enter")
family.v <-which(hyde.words.v == "smiled")
court.v <-which(hyde.words.v == "court")
really.v <-which(hyde.words.v == "really")
windows.v <-which(hyde.words.v == "windows")
its.v <-which(hyde.words.v == "it's")
childs.v <-which(hyde.words.v == "child's")
point.v <-which(hyde.words.v == "point")
best.v <-which(hyde.words.v == "best")
topic.sixteen.v <-c(enfield.v, cheque.v, family.v, court.v, really.v, windows.v, its.v, childs.v, point.v, best.v)
sixteen.count.v <-rep(NA,length(n.time.v))
sixteen.count.v[topic.sixteen.v] <- 1
plot(sixteen.count.v, main="Dispersion plot of Topic 16 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 16", type="h", ylim=c(0,1), yaxt='n')

##Create Plot for Topic 17##
suddenly.v <-which(hyde.words.v == "clothes")
death.v <-which(hyde.words.v == "enter")
throw.v <-which(hyde.words.v == "smiled")
hold.v <-which(hyde.words.v == "court")
heard.v <-which(hyde.words.v == "really")
sort.v <-which(hyde.words.v == "windows")
far.v <-which(hyde.words.v == "it's")
knew.v <-which(hyde.words.v == "child's")
true.v <-which(hyde.words.v == "point")
freshness.v <-which(hyde.words.v == "best")
topic.seventeen.v <-c(enfield.v, cheque.v, family.v, court.v, really.v, windows.v, its.v, childs.v, point.v, best.v)
seventeen.count.v <-rep(NA,length(n.time.v))
seventeen.count.v[topic.seventeen.v] <- 1
plot(seventeen.count.v, main="Dispersion plot of Topic 17 in Jekyll and Hyde", xlab="Novel Time", ylab="Topic 17", type="h", ylim=c(0,1), yaxt='n')